#!/bin/bash
ONLY_ONCE=0
for arg in $*; do
  if test "$arg" = "--once"; then
    ONLY_ONCE=1
  fi
done

function puts()
{
  if test ! -z "$SILENT"; then
    echo $*
  fi
}
CONNECTED=0
HEADPHONES_MAC=D0:8A:55:63:48:61
function attempt_connect () {
  already_connected="$(bluetoothctl info $HEADPHONES_MAC | grep Connected | awk '{print $2}')"
  if test "$already_connected" = "yes"; then
    if test "$CONNECTED" = "0"; then
      restart-pulseaudio
      CONNECTED=1
    fi
    puts "$HEADPHONES_MAC already connected!"
    return
  fi
  result="$(bluetoothctl --timeout 5 connect $HEADPHONES_MAC)";
  if test ! -z "$(echo $result | grep "successful")"; then
    sleep 5
    if test "$CONNECTED" = "0"; then
      puts "restarting poop audio"
      restart-pulseaudio
      CONNECTED=1
    fi
    if test "$ONLY_ONCE" = "1"; then
      echo "performed once-off connection; exiting"
      exit 0
    fi
    puts "connected $HEADPHONES_MAC"
    sleep 10
  else
    puts "no connect!"
    CONNECTED=0
  fi
}

if test -z "$SILENT"; then
  echo "Running in SILENT mode. Set env var SILENT to anything to see output..."
fi

while true; do
  if test -z "$SILENT"; then
    attempt_connect &> /dev/null
  else
    attempt_connect
  fi
  sleep 5
done
