#!/bin/zsh
if test -z "$PROFILE"; then
  if test ! -z "$SMALLER"; then
    PROFILE="General/HQ 720p30 Surround"
  else
    PROFILE="General/HQ 1080p30 Surround"
  fi
fi

if test -z "$HANDBRAKE"; then
  HANDBRAKE=$(which HandBrakeCLI)
fi

if test ! -f "$HANDBRAKE"; then
  echo "Can't find HandBrakeCLI in the path )':"
  exit 1
fi

function clear_line()
{
    echo -n "\r                                                                                                          \r"
}

function truncate_to_fit()
{
  SHORT=$(echo $1 | cut -d'/' -f5-)
  let SPACE="$COLUMNS-12"
  TEST=${SHORT:0:$SPACE}
  if test "$SHORT" != "$TEST"; then
    echo "${TEST}"
  else
    echo "$SHORT"
  fi
}


function reencode()
{
  filepath="$1"
  CODEC=$(mediainfo "$filepath" | grep -A5 Video | grep Format | grep -v Info | grep -v profile | awk '{print $3}' | tr '[:upper:]' '[:lower:]')
  # SHORT=$(echo $filepath | cut -d'/' -f5-)
  SHORT=$(truncate_to_fit $filepath)
  if test -z "$SHORT"; then
    SHORT="$filepath"
  fi
  if test -z "$QUIET"; then
    clear_line
    echo -n "inspect: $SHORT"
  fi
  IS_HEVC=0
  if test ! -z "$(echo $CODEC | grep -i hevc)"; then
    IS_HEVC=1
  fi
  if test $IS_HEVC = "1" || test ! -z "$FORCE"; then
    clear_line
    if test -z "$FORCE"; then
      echo "Re-encode: \"$SHORT\""
    else
      echo "Re-encode (forced): \"$SHORT\""
    fi
    FILENAME="$(basename $filepath)"
    OUTFILE="${FILENAME%.*}.mp4"
    TMPFILE="/tmp/$OUTFILE"
    LOGFILE="/tmp/re-encode__${FILENAME%.*}.log"
    if test -z "$OUTDIR"; then
      TARGET="$(dirname $filepath)/$OUTFILE"
    else
      TARGET="$OUTDIR/$OUTFILE"
    fi
    if test -f "$TARGET"; then
      echo "$TARGET already exists... skipping"
      return 0
    fi
    CMD="nice -n 19 $HANDBRAKE -Z \"$PROFILE\" -i \"$filepath\" -o \"$TMPFILE\" &> \"$LOGFILE\""
    if test ! -z "$DEBUG"; then
      echo "cmd: $CMD"
    fi
    if nice -n 19 $HANDBRAKE -Z "$PROFILE" -i "$filepath" -o "$TMPFILE" &> "$TMPFILE.log"; then
      if mv "$TMPFILE" "$TARGET"; then
        if test ! -z "$KEEP_ORIGINAL"; then
          return 0
        fi
        if rm $filepath; then
          return 0
        fi
        RET=$?
        echo "Cannot remove $filepath"
        return $RET
      else
        RET=$?
        echo "Cannot move $TMPFILE to $TARGET"
        return $RET
      fi
    else
      RET=$?
      echo "Re-encode for $filepath fails!"
      echo "Logfile at $LOGFILE contains:"
      cat "$LOGFILE"
      echo "cmdline was: $CMD"
      return $RET
    fi
  else
    if test -z "$LEAVE_STATUS"; then
      clear_line
    fi
  fi
}

if test ! -f "$1"; then
  echo "$1 is not a file )':"
  exit 1
fi
reencode "$1"
