#!/bin/bash
ONLY_ONCE=0
for arg in $*; do
  if test "$arg" = "--once"; then
    ONLY_ONCE=1
  fi
done

HEADPHONES_MAC=D0:8A:55:63:48:61
function attempt_connect () {
  already_connected="$(bluetoothctl info $HEADPHONES_MAC | grep Connected | awk '{print $2}')"
  if test "$already_connected" = "yes"; then
    if test ! -z "$SILENT"; then
      echo "$HEADPHONES_MAC already connected!"
    fi
    return
  fi
  result="$(bluetoothctl --timeout 5 connect $HEADPHONES_MAC)";
  if test ! -z "$(echo $result | grep "successful")"; then
    if test "$ONLY_ONCE" = "1"; then
      echo "performed once-off connection; exiting"
      exit 0
    fi
    if test -z "$SILENT"; then
      echo "connected $HEADPHONES_MAC"
    fi
  fi
}

if test -z "$SILENT"; then
  echo "Running in SILENT mode. Set env var SILENT to anything to see output..."
fi

while true; do
  if test -z "$SILENT"; then
    attempt_connect &> /dev/null
  else
    attempt_connect
  fi
  sleep 5
done
