#!/bin/bash
function die() {
  echo "$1"
  exit 1
}

function now() {
  echo "$(date -Ins | sed -e 's/,/ /' | awk '{ print $1 }')Z"
}

TOKEN="$1"
if test -z "$TOKEN"; then
  TOKEN="$CLEAR_GITHUB_NOTIFICATIONS_TOKEN"
fi
if test -z "$TOKEN"; then
  die "Please either provide a token as the only argument to this script or set it on the environment variable CLEAR_GITHUB_NOTIFICATIONS_TOKEN"
fi

curl -L -X PUT \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/notifications \
  -d "{\"last_read_at\":\"$(now)\",\"read\":true}"
