#!/bin/bash

RCFILE=${HOME}/.delayed_autostart

if test ! -f ${RCFILE}; then
	exit 1
fi

DELAY=30
STATE="start"
START=""
INIT=""

while read -r line; do
	if test -z "$line"; then
		continue
	fi
	if test -n "$(echo $line | grep '^#.*')"; then
		continue
	fi
	case "$line" in
		"[conf]")
			STATE="config"
			continue
		;;
    "[init]")
      STATE="init"
      continue
    ;;
		"[start]")
			STATE="start"
			continue
		;;
	esac

	case "$STATE" in
		"config")
			eval $line
		;;
    "init")
      INIT="${INIT}${line}"
    ;;
		"start")
			START="${START}${line}\n"
		;;
	esac
done < $RCFILE

LOGDIR=/tmp/delayed_autostart_logs
if ! test -e $LOGDIR; then
    mkdir $LOGDIR
fi

function run_lines() {
  LABEL=$1
  LINES=$2
  if test -z "$LINES"; then
    return
  fi
  echo "Running $LABEL"
  echo -e "$LINES" | while read -r line; do
    if test -z "$line"; then
      continue
    fi
      LOGFILE="$LOGDIR/$(echo $line | sed -e 's/ /-/g' | sed -e 's/\//-/g')"
    $line &> $LOGFILE &
  done
}

run_lines "Init..." "$INIT"

echo "Waiting $DELAY seconds..."
sleep $DELAY
run_lines "Start" "$START"

