#!/bin/env python
import sys
import os
import json
from os import path
import json
import subprocess

def find_package_json():
  current = os.getcwd()
  last = ""
  while last != current:
    last = current
    test = path.join(current, "package.json")
    if path.isfile(test):
      return test
    current = path.dirname(current)
  return ""

def load_json(at):
  with open(at) as fp:
    raw = fp.read()
    return json.loads(raw)

def print_array(a, title):
  if len(a) == 0:
    return
  print(title)
  for i in a:
    print(f"- {i}")

def generate_deps_lines(deps, fetch_latest_version=False) -> list[str]:
  result = []
  for key in sorted(deps.keys()):
    if fetch_latest_version:
      proc = subprocess.run(["npm", "show", "--json", key ], capture_output=True)
      pkginfo = json.loads(proc.stdout)
      result.append(f"{key}: {deps[key]} ({pkginfo["versions"][-1]})")
    else:
      result.append(f"{key}: {deps[key]}")
  return result

def perform_dep_search(deps, text, title, fetch_latest_version=False):
  if text is None:
    print_array(generate_deps_lines(deps, fetch_latest_version), title)
    return
  collected = []
  for key in deps.keys():
    lower = key.lower()
    if lower.find(text) > -1:
      collected.append(f"{key}: {deps[key]}")
  print_array(collected, title)

def perform_sectional_search(package, text, section, fetch_latest_version=False):
  if section in package:
    perform_dep_search(package[section], text, section, fetch_latest_version)

def perform_search(package, text, fetch_latest_version=False):
  perform_sectional_search(package, text, "dependencies", fetch_latest_version)
  perform_sectional_search(package, text, "devDependencies", fetch_latest_version)

if __name__ == "__main__":
  package_json = find_package_json()
  if package_json == "":
    print(f"no package.json found whilst traversing up from {os.getcwd()}")
    sys.exit(1)

  fetch_latest_version = "-v" in sys.argv or "--verbose" in sys.argv
  show_help = "-h" in sys.argv or "--help" in sys.argv

  if show_help:
    print("Usage: dep {--verbose} {<search>}")
    print("       run without args: prints all dependencies")
    print("       dep foo: show packages containing foo (version & type of dependency)")
    print("       dep --verbose foo: show packages containing 'foo' and print their upstream versions")
    sys.exit(0)

  search_args = []
  for arg in sys.argv[1:]:
    if arg.startswith("-"):
      continue
    search_args.append(arg)

  pkg = load_json(package_json)
  if len(search_args) > 0:
    if len(search_args) == 1:
      perform_search(pkg, search_args[0], fetch_latest_version)
    else:
      for item in search_args:
        print(f"search: {item}")
        perform_search(pkg, item, fetch_latest_version)
  else:
    perform_search(pkg, None, fetch_latest_version)
