#!/bin/bash
UPS_NAME=mecer
UPS_USER=root
UPS_PASS=root

fetch_beeper_state()
{
  echo $(upsc $UPS_NAME | grep beeper.status | awk '{print $2}')
}

STARTING_STATE="$(fetch_beeper_state)"
if test "$STARTING_STATE" = "disabled"; then
  echo "Beeper is already disabled..."
  exit 0
fi

function attempt_disable()
{
  if test "$(fetch_beeper_state)" = "enabled"; then
    echo "beeper is enabled... disabling"
    upscmd -u $UPS_USER -p $UPS_PASS $UPS_NAME beeper.toggle
  fi
}

GIVE_UP=0
function verify()
{
  if test "$(fetch_beeper_state)" != "disabled"; then
    echo "ERROR: beeper remains enabled"
    echo "- attempt device reset..."
    if test $GIVE_UP -eq 0; then
      ./reset-ups-usb-device
      attempt_disable
      sleep 5
      verify
    fi
  fi
}

attempt_disable
sleep 5
verify


