#! /bin/sh
### BEGIN INIT INFO
# Provides:          divorced_mount
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: mount stuff from fstab which has been set to noauto to prevent bootlock
### END INIT INFO

# Don't run if we're going to start an Android LXC container:
[ ! -f /etc/init/lxc-android-config.conf ] || exit 0

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

AVAILABLE="/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors"

case "$1" in
    start)
    	for m in $(grep noauto /etc/fstab | grep mnt | awk '{print $2}'); do
		echo "Mounting $m..."
		mount $m
	done
        ;;
    restart|reload|force-reload)
		$0 stop
		$0 start
        ;;
    stop)
    	for m in $(grep noauto /etc/fstab | grep mnt | awk '{print $2}'); do
		echo "Mounting $m..."
		umount $m
	done
	;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
