#!/bin/bash
CONNECTORS=( $(xrandr | grep "\sconnected" | cut -d " " -f 1) )
FLAG="$1"
if test -z "$FLAG"; then
  FLAG="on"
fi
for c in ${CONNECTORS[@]}; do
  xrandr --output "$c" --set TearFree $FLAG
done
