#!/bin/bash
echo Breaking up the FLAC
CUE=$(ls -w1 *.cue | head -n 1)
FLAC=$(ls -w1 *.flac | head -n 1)
echo Album: $FLAC
echo CUE: $CUE
cuebreakpoints "$CUE" | shnsplit -o flac "$FLAC"
echo Please tag before mp3 can continue
pause

for a in split*.flac; do

  # get the tags
  ARTIST=$(metaflac "$a" --show-tag=ARTIST | sed s/.*=//g)
  TITLE=$(metaflac "$a" --show-tag=TITLE | sed s/.*=//g)
  ALBUM=$(metaflac "$a" --show-tag=ALBUM | sed s/.*=//g)
  GENRE=$(metaflac "$a" --show-tag=GENRE | sed s/.*=//g)
  TRACKNUMBER=$(metaflac "$a" --show-tag=TRACKNUMBER | sed s/.*=//g)
  DATE=$(metaflac "$a" --show-tag=DATE | sed s/.*=//g)

  # give output correct extension
  #OUTF="${a[@]/%flac/mp3}"
  OUTF="${ARTIST} - ${TRACKNUMBER} - ${TITLE}.mp3"

  # stream flac into the lame encoder
  flac -c -d "$a" | lame -V0 --add-id3v2 --pad-id3v2 --ignore-tag-errors \
    --ta "$ARTIST" --tt "$TITLE" --tl "$ALBUM"  --tg "${GENRE:-12}" \
    --tn "${TRACKNUMBER:-0}" --ty "$DATE" - "$OUTF"
done

mv "$FLAC" "${FLAK}.bak"
rm *.flac

echo Check before I clean up...
pause
rm "$FLAC"
rm "$CUE"
rm *.log
