#!/bin/bash
MODE="$1"
if test -z "$MODE"; then
  echo "Game mode on or off?"
  read selection discarded
  MODE="$selection"
fi
MODE="$(echo $MODE | tr [:upper:] [:lower:])"

case "$MODE" in
  on)
    echo "game mode ON"
      cp ~/.xbindkeysrc.game-mode-on ~/.xbindkeysrc
    ;;
  off)
    echo "game mode OFF"
      cp ~/.xbindkeysrc.game-mode-off ~/.xbindkeysrc
    ;;
  *)
    echo "please invoke with 'on' or 'off'"
    exit 1
    ;;
 esac

 $(dirname $0)/restart-xbindkeys
