#!/bin/bash
STATEFILE=/tmp/headphones-battery-last-state
PERC=$(headsetcontrol -b --short-output)
if test "$PERC" -lt 0; then
  if test -f "$STATEFILE"; then
    echo "🎧 ($(cat $STATEFILE)%)"
  else
    echo "🎧 idle"
  fi
else
  echo "🎧 ${PERC}%"
  echo $PERC > $STATEFILE
fi
