#!/bin/bash
if test -z "$1"; then
  echo "arg1 is '$1'"
  VENV_UTIL="$(dirname "$0")/venv"
  if ! test -f "$VENV_UTIL"; then
    echo "venv not found at $VENV_UTIL"
    exit 1
  fi
  $VENV_UTIL "$0" start
  exit $?
fi

case "$1" in
  start)
    pip install jupyter ipykernel jupyterlab-vim
    python -m ipykernel install --user --name "venv-$(basename "$(pwd)")"
    jupyter notebook
    ;;
  *)
    echo "invalid argument: $1"
    exit 2
    ;;
esac
