#!/bin/bash
if ! test -d venv; then
  echo "venv not found... creating..."
  python -m venv venv
  echo "activating venv"
  source venv/bin/activate
  echo "installing jupyter into venv"
  pip install jupyter ipykernel
  echo "creating kernel for jupyter"
  python -m ipykernel install --user --name venv
else
  source venv/bin/activate
fi

jupyter notebook
