#!/usr/bin/python3
# vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
import os
import sys
import re
import subprocess
import shutil
import re

def would(str: str) -> None:
    print("Would: %s" % str)


def purge_dpkg(ver: str) -> None:
    if not have_dpkg():
        return
    print("Purging headers for %s" % ver)
    cmd = "dpkg --purge linux-image-%s" % ver
    if DRY_RUN:
        would(cmd)
    else:
        os.system(cmd)

    print("Purging image for %s" % ver)
    cmd = "dpkg --purge linux-headers-%s" % ver
    if DRY_RUN:
        would(cmd)
    else:
        os.system(cmd)

    print("Purging modules for %s" % ver)
    cmd = "dpkg --purge linux-modules-%s" % ver
    if DRY_RUN:
        would(cmd)
    else:
        os.system(cmd)


def have_dpkg() -> bool:
    proc = subprocess.run(
        ["which", "dpkg"],
        capture_output=True
    )
    return proc.returncode == 0


def remove_modules(ver: str, base: str):
    print(yellow("Picking off straggling modules for %s" % ver))
    modules_dir = os.path.join(base, ver)
    contents = sorted(ls_recursive(modules_dir), reverse=True)
    if DRY_RUN:
        for f in contents:
            would(red("remove: %s" % f))
        would(red("remove: %s" % (modules_dir)))
        return
    shutil.rmtree(modules_dir)


def remove_boot_detritus(ver: str):
    print(yellow("Cleaning out /boot for %s" % ver))
    contents = ls_recursive("/boot")
    for f in contents:
        if not ver in f:
            continue
        if DRY_RUN:
            would(red("remove: %s" % (f)))
        else:
            os.remove(f)


def remove_kernel_sources(ver: str) -> None:
    source_dir = re.sub("-(x86_64|i386)", "", "/usr/src/linux-%s" % ver)
    if not os.path.isdir(source_dir):
        print(yellow("No kernel sources found at %s" % source_dir))
        return

    if DRY_RUN:
        would(red("remove %s" % source_dir))
        return

    print(yellow("Removing sources from %s" % source_dir))
    shutil.rmtree(source_dir)


def ls_recursive(dir: str) -> list[str]:
    stack = [dir]
    ret = []
    while stack:
        this_dir = stack.pop(0)
        if not os.path.isdir(this_dir):
            continue
        for f in sorted(os.listdir(this_dir)):
            path = os.path.join(this_dir, f)
            ret.append(path)
            if os.path.isdir(path):
                stack.append(path)
    return ret

def to_ints(str: str) -> list[int]:
  result: list[int] = []
  parts = re.split(r"[.-]", str)
  for part in parts:
    try:
      result.append(int(part))
    except ValueError:
      pass
  return result

def version(path: str) -> str:
    # parts = path.split(os.sep)
    # last = re.sub(r"-.*$", "", parts[-1])
    # parts = map(int, last.split("."))
    path_parts = path.split(os.sep)
    parts = to_ints(path_parts[-1])

    result = ""
    for part in parts:
        local_part = str(part)
        while len(local_part) < 4:
            local_part = "0" + local_part
        result = result + local_part
    return result


def usage() -> None:
    print("Usage: %s {opts}" % (os.path.basename(sys.argv[0])))
    print(" where opts are of")
    print(" -d / --dryrun:      report only, don't actually delete or remove anything")
    print(" -k / --keep:        specify how many versions of the kernel to keep")
    print("                      (default 2)")
    print(" -md / --modulesdir  specify location of your modules")
    print("                      (default /lib/modules)")


def red(s: str) -> str:
    return color(s, 31)


def green(s: str) -> str:
    return color(s, 32)


def yellow(s: str) -> str:
    return color(s, 33)


def blue(s: str) -> str:
    return color(s, 34)


def purple(s: str) -> str:
    return color(s, 35)


def cyan(s: str) -> str:
    return color(s, 36)


def white(s: str) -> str:
    return color(s, 37)


def color(s: str, c: int) -> str:
    return "\033[1;%im%s\033[1;0m" % (c, s)


def try_convert_to_int(s: str) -> int:
    try:
        return int(s)
    except ValueError:
        print("%s is not a valid number" % (s))
        sys.exit(1)


def restarted_as_root():
    user = (
        subprocess
        .check_output("whoami")
        .decode("utf-8")
        .strip()
    )
    if user == "root":
        return False
    args = "sudo -p \"Your password is required to continue: \" " + \
        " ".join(sys.argv)
    os.system(args)
    return True

if __name__ == "__main__":
    if restarted_as_root():
        sys.exit()
    global DRY_RUN
    keep = 2
    basedir = "/lib/modules"
    last_arg = ""
    yes = False
    for arg in sys.argv[1:]:
        if ["-k", "--keep", "-keep",
                "-md", "--modulesdir", "-modulesdir"].count(arg) > 0:
            last_arg = arg
            continue
        if ["-h", "-help", "--help"].count(arg) > 0:
            usage()
            sys.exit(0)
        if ["-d", "--dryrun"].count(arg) > 0:
            DRY_RUN = True
        if ["-k", "--keep", "-keep"].count(last_arg) > 0:
            keep = try_convert_to_int(arg)
            last_arg = arg
        if ["-md", "--modulesdir", "-modulesdir"].count(last_arg) > 0:
            basedir = arg
            last_arg = arg
        if ["-y", "--yes"].count(arg) > 0:
            yes = True
    if not os.path.isdir(basedir):
        print("Can't find modules base at %s; specify with -md" % (basedir))
        sys.exit(2)

    available_kernels = sorted(os.listdir(basedir), reverse=True, key=version)

    if len(available_kernels) <= keep:
        if len(available_kernels) == 0:
            print("No kernel images found?!")
        else:
            if len(available_kernels) == 1:
                s = ""
            else:
                s = "s"
        print("You only have %i kernel image%s: nothing to do" %
              (len(available_kernels), s))
        sys.exit(0)

    to_remove = available_kernels[keep:]

    would = "would"
    if yes:
        would = "will"

    if DRY_RUN:
        print(cyan("DRY RUN ONLY - NON-DESTRUCTIVE"))
    elif not yes:
        print(red("Please verify before continuing:"))
    print("Operation %s purge the following kernels:" % (would))
    for k in to_remove:
        print(red("  %s" % (k)))
    print("The following kernels %s be left:" % (would))
    for k in available_kernels[:keep]:
        print(green("  %s" % (k)))

    if not yes:
        sys.stdout.write("Are you sure you want to continue ? (y/N) ")
        sys.stdout.flush()
        ans = sys.stdin.readline().strip().lower()
        if len(ans) == 0 or ans[0] != "y":
            print("Bailing out")
            sys.exit(0)

    for k in to_remove:
        purge_dpkg(k)
        remove_modules(k, basedir)
        remove_boot_detritus(k)
        remove_kernel_sources(k)
    print(yellow("Update GRUB"))
    if DRY_RUN:
        would(purple("update grub"))
    else:
        os.system("grub-mkconfig -o /boot/grub/grub.cfg")
        print(green(">> done <<"))
