#!/usr/bin/python
import os
import sys
import time

if len(sys.argv[1:]) == 0:
	print("Mention at least one wireless adapter!")
	sys.exit(1)

while True:
	try:
		to_print = ""
		for adapter in sys.argv[1:]:
			if len(to_print) > 0:
				to_print += "\t"
			info = os.popen("iwconfig %s" % adapter).read()
			if len(info) == 0:
				to_print += ("%s: no info" % adapter)
				continue
			lines = info.split("\n")
			for line in lines:
				if line.count("Link Quality") == 0:
					continue
				parts = line.split("=")
				qual = parts[1].split(" ")[0]
				parts = qual.split("/")
				perc = (float(parts[0]) * 100.0) / float(parts[1])
				to_print += ("%s: %i %%" % (adapter, perc))
				break
		sys.stdout.write("\r%s\r" % (" " * 72))
		sys.stdout.write(to_print)
		sys.stdout.flush()
		time.sleep(1)
	except KeyboardInterrupt:
		sys.exit(0)
