#!/bin/bash
MOUNTPOINT=/home/daf/GoogleDrive
if test ! -z "$(mount | grep $MOUNTPOINT)"; then
    echo "google drive already mounted at $MOUNTPOINT";
    exit 0
fi
google-drive-ocamlfuse /home/daf/GoogleDrive
