#!/bin/bash
CACHEFILE=/tmp/mousebat-perc.cache
REPO=~/code/opensource/rivalcfg

if test -z "$NOCACHE"; then
  if test -f "$CACHEFILE"; then
    CACHEFILE_AGE="$(( `date +%s` - `stat -L --format %Y $CACHEFILE` ))"
    if test $CACHEFILE_AGE -lt 30; then
      cat $CACHEFILE
      exit 0
    fi
  fi
fi

BATTERY_PERCENT=$(solaar show | grep Battery | head -n 1 | awk '{print $2}' | grep -o '[0-9]*')
if test -z "$BATTERY_PERCENT"; then
  echo "idle" | tee $CACHEFILE
else
  echo "$BATTERY_PERCENT%" | tee $CACHEFILE
fi
cd - &> /dev/null
