#!/bin/bash
PROTON=$(find ~/.steam/steam/steamapps/common -name proton | sort --reverse | head -n 1)
if test -z "$PROTON"; then
  echo "can't find proton )':"
  exit 1
fi
export STEAM_COMPAT_DATA_PATH=~/.proton
"$PROTON" run $1
