#!/bin/bash
if test "$(whoami)" != "root"; then
  sudo -p "Your password is required to continue: " $0 $@
  exit $?
fi
emerge -e --keep-going --quiet-build @world $*

REBUILD_KERNEL=$(dirname $0)/rebuild-kernel
if test -f $REBUILD_KERNEL; then
  $REBUILD_KERNEL
fi
