#!/bin/bash
TARGET="$1"
RENICE_TO="$2"
if test -z "$1" || test -z "$2"; then
  echo "Usage: renice-all {app} {level}"
  echo "  eg: renice-all firefox -10"
  exit 1
fi

function exit_bad_renice()
{
  echo "renice value must be an integer between 19 (lowest priority) and -19 (highest priority), inclusive (provided value was: $RENICE_TO)"
  exit 2
}

NON_NUMERICS=$(echo $RENICE_TO | sed -e 's/^-//' | sed -e 's/[0-9]//g');
if test ! -z "$NON_NUMERICS"; then
  exit_bad_renice
fi
if test "$RENICE_TO" -lt -19; then
  exit_bad_renice
fi
if test "$RENICE_TO" -gt 19; then
  exit_bad_renice
fi

if test "$(whoami)" != "root" && test "$RENICE_TO" -lt 0; then
  sudo -p "Your password is required to elevate process niceness to negative values: " $0 $1 $2
  exit $?
fi

let RENICED=0
for pid in $(pidof $1); do
  let RENICED="$RENICED + 1"
  renice -n $RENICE_TO -p $pid
done

if test $RENICED -eq 0; then
  echo "no process matches found for $TARGET"
  exit 3
fi

if which ionice &> /dev/null; then
  IONICE_LOOKUP=(
    ["0"]="realtime,1"        # -19
    ["1"]="realtime,2"        # -18
    ["2"]="realtime,3"        # -17
    ["3"]="realtime,4"        # -16
    ["4"]="realtime,5"        # -15
    ["5"]="realtime,6"        # -14
    ["6"]="realtime,7"        # -13
    ["7"]="realtime,8"        # -12
    ["8"]="best-effort,0"     # -11
    ["9"]="best-effort,0"     # -10
    ["10"]="best-effort,1"    # -9
    ["11"]="best-effort,1"    # -8
    ["12"]="best-effort,2"    # -7
    ["13"]="best-effort,2"    # -6
    ["14"]="best-effort,3"    # -5
    ["15"]="best-effort,3"    # -4
    ["16"]="best-effort,4"    # -3
    ["17"]="best-effort,4"    # -2
    ["18"]="best-effort,4"    # -1
    ["19"]="none,0"           # 0
    ["20"]="best-effort,5"    # 1
    ["21"]="best-effort,5"    # 2
    ["22"]="best-effort,5"    # 3
    ["23"]="best-effort,6"    # 4
    ["24"]="best-effort,6"    # 5
    ["25"]="best-effort,6"    # 6
    ["26"]="best-effort,7"    # 7
    ["27"]="best-effort,7"    # 8
    ["28"]="best-effort,7"    # 9
    ["29"]="idle,0"           # 10
    ["30"]="idle,0"           # 11
    ["31"]="idle,0"           # 12
    ["32"]="idle,0"           # 13
    ["33"]="idle,0"           # 14
    ["34"]="idle,0"           # 15
    ["35"]="idle,0"           # 16
    ["36"]="idle,0"           # 17
    ["37"]="idle,0"           # 18
    ["38"]="idle,0"           # 19
  )


  let IDX="$RENICE_TO + 19"
  IFS="," read -ra idleConfig <<< "${IONICE_LOOKUP[$IDX]}"
  echo "ionicing to: ${idleConfig[0]}, priority ${idleConfig[1]}"

  for pid in $(pidof $1); do
    let IONICED="$IONICED + 1"
    ionice -p $pid -c ${idleConfig[0]} -n ${idleConfig[1]}
  done
else
  echo "ionice not found - no io-scheduling changes made"
fi
echo "reniced $RENICED $TARGET processes"
