#!/bin/bash
function die() {
  echo "$2"
  exit $1
}
function spin() {
  case "$SPIN_CHAR" in
    "|")
      SPIN_CHAR="/"
      ;;
    "/")
      SPIN_CHAR="-"
      ;;
    "-")
      SPIN_CHAR="\\"
      ;;
    *)
      SPIN_CHAR="|"
      ;;
  esac
  echo -en "\r    \r${SPIN_CHAR}"
  sleep 0.1
}
function install() {
  TARGET="$1"
  LOCAL_LINK="${HOME}/.local/bin/${TARGET}"
  if test -e "$LOCAL_LINK"; then
    read -p "$LOCAL_LINK already exists. Replace it? (Y/n) " answer
    answer="$(echo $answer | tr [:upper:] [:lower:])"
    if test -z "$answer" || test "$answer" == "y"; then
      rm "$LOCAL_LINK"
    fi
  fi
  echo "installing script at $LOCAL_LINK"
  read -r -d '' SCRIPT <<EOF
#!/bin/bash
$(realpath $0) $TARGET \$1
EOF
  echo "$SCRIPT" > "$LOCAL_LINK";
  chmod +x "$LOCAL_LINK"
}

TARGET="$1"

if test "$TARGET" = "install"; then
  install $2
  exit 0
fi

if test -z "$TARGET"; then
  die 1 "No tool specified. Run like so: $0 webstorm"
fi

JETBRAINS_HOME="$HOME/.local/share/JetBrains/Toolbox/apps/"
if test ! -d "$JETBRAINS_HOME"; then
  die 2 "JetBrains scripts not found at: $JETBRAINS_HOME"
fi

for f in $(find "$JETBRAINS_HOME" -name $TARGET); do
  if test -f "$f" && test -x "$f"; then
    FULL_PATH="$f"
    break
  fi
done

if test -z "$FULL_PATH"; then
  die 3 "FATAL: cannot find tool stub for ${TARGET}"
fi

echo "Starting '$FULL_PATH' ${@:2}"
"$FULL_PATH" "${@:2}" &> /dev/null &
CHILD_PID="$!"

echo "${TARGET} started as pid: ${CHILD_PID}"

while ps -p $CHILD_PID &> /dev/null; do
  spin
  if wmctrl -lp | awk '{print $3}' | grep $CHILD_PID &> /dev/null; then
    echo -e "\r    \r\n"
    exit 0
  fi
done
