#!/bin/zsh

# relies on pulse device 1 being speakers and 0 being usb headphones
# (which is a little odd, come to think about it)

function runcmd () {
  echo -n "Setting default sinki ($2)..."
  if ! /usr/bin/pacmd $@ > /dev/null; then
    echo " (fail)"
    echo "  Unable to run command:"
    echo "  /usr/bin/pacmd $@"
  else
    echo " (ok)"
  fi
}

if test -z "$1"; then
  echo "Usage: $0 <card index>"
  exit 2
fi

CARD="$1"
if test "$CARD" = "headphones"; then
  CARD=0
elif test "$CARD" = "speakers"; then
  CARD=1
elif test "$CARD" = "combined"; then
  CARD=2
fi

# switch the default sink
runcmd "set-default-sink" $CARD

# now switch over existing streams
echo -n "Moving all sink inputs"
for src in $(pacmd list-sink-inputs | grep index: | cut -f 2 --delimiter=':'); do
  echo -n "."
  if pacmd move-sink-input $src $CARD &> /dev/null; then
    echo -n "."
  else
    echo -n "x"
  fi
done
echo " (done)"

