#!/usr/bin/python
import io
import os
import subprocess
import re


def debug(s):
    if os.environ.get("DEBUG") == "1":
        print(s)


def read_devices():
    proc = subprocess.Popen(["openrgb", "-l"], stdout=subprocess.PIPE)
    result = []
    device_matcher = re.compile("^\\d:")

    for line in io.TextIOWrapper(proc.stdout, encoding="utf-8"):
        if device_matcher.match(line) is None:
            continue

        parts = line.strip().split(":")
        result.append({
            "id": parts[0],
            "name": ":".join(parts[1:]).strip()
        })
    return result


def generate_cli(devices):
    mode = "static"
    ram_colors = ["FF1E00", "FF1400", "FF0A00", "FF0000"]
    board_color = "FF2800"
    ram_matcher = re.compile(".*ASUS Aura DRAM.*", re.IGNORECASE)
    board_matcher = re.compile(".*AORUS ELITE.*", re.IGNORECASE)
    result = []
    for device in devices:
        if ram_matcher.match(device["name"]):
            if len(ram_colors) == 0:
                raise Exception("Ran out of RAM colors?")
            debug("adding ram at %s: %s" % (device["id"], ram_colors[0]))
            result.extend(["-d", device["id"], "-m", mode, "-c", ram_colors[0]])
            ram_colors = ram_colors[1:]
        elif board_matcher.match(device["name"]):
            debug("adding board at %s: %s" % (device["id"], board_color))
            result.extend(["-d", device["id"], "-m", mode, "-c", board_color])
    return result


def run_openrgb_with(options):
    cli = ["openrgb"]
    cli.extend(options)
    debug("running cmd: %s" % (" ".join(cli)))
    proc = subprocess.Popen(cli, stdout=subprocess.PIPE)
    proc.wait()
    lines = []
    for line in io.TextIOWrapper(proc.stdout, encoding="utf-8"):
        line = line.strip()
        debug(line)
        lines.append(line)
    if proc.returncode != 0:
        raise Exception("unable to run openrgb with cli: " + " ".join(options) + "\n" + "\n".join(lines))


def main():
    devices = read_devices()
    cli = generate_cli(devices)
    run_openrgb_with(cli)


main()
