#!/bin/zsh

# relies on pulse device 1 being speakers and 0 being usb headphones
# (which is a little odd, come to think about it)

function runcmd () {
  echo -n "Setting default sinki ($2)..."
  if ! /usr/bin/pacmd $@ > /dev/null; then
    echo " (fail)"
    echo "  Unable to run command:"
    echo "  /usr/bin/pacmd $@"
  else
    echo " (ok)"
  fi
}

if test -z "$1"; then
  echo "Usage: $0 <card index>"
  exit 2
fi

CARD="$1"
if test "$CARD" = "headphones"; then
  CARD=0
elif test "$CARD" = "speakers"; then
  CARD=1
elif test "$CARD" = "combined"; then
  CARD=2
fi

# switch the default sink
runcmd "set-default-sink" $CARD

# now switch over existing streams
echo -n "Moving all sink inputs"
for src in $(pacmd list-sink-inputs | grep index: | cut -f 2 --delimiter=':'); do
  echo -n "."
  if pacmd move-sink-input $src $CARD &> /dev/null; then
    echo -n "."
  else
    echo -n "x"
  fi
done
echo " (done)"

# move kmix (requires that indexes match up... this is empirical)
killall -15 kmix
#KMIXRC=/home/daf/.kde/share/config/kmixrc
#if test "$CARD" = "1"; then
#  echo -n "kmixrc: set master to speakers"
#  if sed $KMIXRC -i -e 's/MasterMixerDevice=.*/MasterMixerDevice=alsa_output.pci-0000_00_14.2.analog-stereo/'; then
#    echo " (ok)"
#  else
#    echo " (fail)"
#  fi
#elif test "$CARD" = "0"; then
#  echo -n "kmixrc: set master to logitech usb"
#  if sed $KMIXRC -i -e 's/MasterMixerDevice=.*/MasterMixerDevice=alsa_output.usb-Logitech_Logitech_USB_Headset-00-Headset.analog-stereo/'; then
#    echo " (ok)"
#  else
#    echo " (fail)"
#  fi
#elif test "$CARD" = "2"; then
#  echo -n "kmixrc: set master to combined"
#  if sed $KMIXRC -i -e 's/MasterMixerDevice=.*/MasterMixerDevice=combined/'; then
#    echo " (ok)"
#  else
#    echo " (fail)"
#  fi
#  # set card volumes to 90%
#  let "vol = 65536 * 0.9"
#  v=${vol/.*}
#  echo "Setting vol to $v"
#  for ((i = 0; $i < 2; i++)); do
#    pacmd set-sink-volume $i $v &> /dev/null
#  done
#
#else
#  echo "Don't know how to mod kmix for card $CARD"
#fi
kmix &> /dev/null &
