#!/bin/sh
if test -z "$1"; then
  echo "Please specify the target to share to"
  echo "eg: $0 /run/media/daf/Target"
  exit 1
fi
BITSPLAT=$(which bitsplat)
if test -z "$BITSPLAT"; then
  echo "Unable to find bitsplat in the path";
  return 2;
fi
CMD="$BITSPLAT --mode opt-in --keep-stale"

SYNCED=0
for src in /mnt/monolith/series /mnt/piggy/series/watched; do
    $CMD -s $src -t $1/series
    if test "$?" -ne 0; then
      exit 2
    fi
    let "SYNCED=SYNCED+1"
done
