#!/bin/sh
if test -z "$1"; then
  echo "Please specify the target to share to"
  echo "eg: $0 /run/media/daf/Target"
  exit 1
fi
MEDESYNC=$(which medesync.py)
if test -z "$MEDESYNC"; then
  echo "Unable to find medesync.py in the path";
  return 2;
fi

SYNCED=0
TARGET="$1"
cd "$TARGET"
for folder in *; do
  if ! test -d "$folder"; then
    continue
  fi
  for src in /mnt/monolith/series /mnt/piggy/series/watched /mnt/archive/series; do
      this_src="$src/$folder"
      if ! test -d "$this_src"; then
        continue
      fi
      echo "checking on $folder from $src"
      ionice -c idle $MEDESYNC -n -s "$this_src" -d "$folder"
      if test "$?" -ne 0; then
        exit 2
      fi
      let "SYNCED=SYNCED+1"
  done
done
cd - &> /dev/null
if test $SYNCED -eq 0; then
  TEST="$TARGET/series"
  if test -d "$TEST"; then
    "$0" "$TEST"
  fi
fi
