#!/bin/sh
TARGET="/mnt/haynes"
AUTO_UNMOUNT=0
if test -z "$(mount | grep $TARGET)"; then
  if ! mount $TARGET &> null; then
    exit 0
  fi
  AUTO_UNMOUNT=1
fi

"$(dirname $0)/share-media" "$TARGET"
if test "$AUTO_UNMOUNT" = "1"; then
  umount $TARGET
fi
