#!/bin/bash
function check_is_root()
{
   if test "$(whoami)" != "root"; then
     sudo -p "Your password is required to continue: " $0 $@
     exit $?
   fi
}

if test -z "$1"; then
  echo "Please specify a device, or enough of a mount identifier"
  exit 1
fi
check_is_root $@

DEVICE=$(mount | grep -i "^$1")
if test -z "$DEVICE"; then
  DEVICE=$(mount | grep -i $1 | awk '{ print $1 }')
fi
if test -z "$DEVICE"; then
  echo "Can't find a device match for $1";
  exit 127
fi

umount $DEVICE
fatsort -c $DEVICE
