#!/bin/sh
if test -z "$1"; then
  WORKDIR="."
else
  WORKDIR="$1"
fi
START="$(pwd)"
cd "$WORKDIR"

find "$WORKDIR" -iname "*.rar" -exec ionice -c idle unrar -o+ x {} \;

FOUND=0
for f in $(find "$WORKDIR" -iname "*.rar"); do
  ((FOUND=FOUND+1))
done

if test "$FOUND" -eq "0"; then
  echo "No rars found )':"
  exit 1
fi

echo "Unrared $FOUND things"

cd "$START"
