#!/bin/sh
function check_is_root()
{
  if test "$(whoami)" != "root"; then
    sudo -p "Your password is required to continue: " $0 $@
    exit $?
  fi
}
check_is_root
grub-mkconfig -o /boot/grub/grub.cfg
