#!/bin/bash
function check_is_root()
{
  if test "$(whoami)" != "root"; then
    sudo -p "Your password is required to continue: " "$0" "$@"
    exit $?
  fi
}
check_is_root

SUFFIX=""
if which emerge &> /dev/null; then
  SUFFIX="gentoo"
fi
if test -z "$SUFFIX" && which pacman &> /dev/null; then
  SUFFIX="arch"
fi
if test -z "$SUFFIX" && which apt-get &> /dev/null; then
  SUFFIX="debian";
fi

if test -z "$SUFFIX"; then
  echo "this script does not support your platform";
  exit 1
fi

$(dirname $0)/update-world.$SUFFIX "$@"
