#!/bin/bash
NO_SYNC=""
ASK="-a"
HELP=""
PRETEND=""
RECEIVING_EMERGE_ARGS=""
EMERGE_ARGS=""
function check_is_root()
{
  if test "$(whoami)" != "root"; then
    echo "You must be root to continue";
    exit -1
  fi
}

for arg in "$@"; do
  if test "$arg" = "--"; then
    RECEIVING_EMERGE_ARGS="yes"
    continue
  fi
  if test ! -z "$RECEIVING_EMERGE_ARGS"; then
    EMERGE_ARGS="$EMERGE_ARGS $arg"
    continue
  fi
  if test "$arg" = "--no-sync" || test "$arg" = "-n"; then
    NO_SYNC=1
    continue
  fi
  if test "$arg" = "--yes" || test "$arg" = "-y"; then
    ASK=""
    continue
  fi
  if test "$arg" = "-p" || test "$arg" = "--pretend"; then
    PRETEND="-p"
    continue
  fi
  if test "$arg" = "-h" || test "$arg" = "--help"; then
    HELP=1
    continue
  fi
  # assume left-over args are to emerge
  EMERGE_ARGS="$EMERGE_ARGS $arg"
done
if test ! -z "$HELP"; then
  echo "Usage: $(dirname $0) [options]"
  echo "OPTIONS:"
  echo " -h, --help          show this screeen and exit"
  echo " -n, --no-sync       skip sync, just emerge updates"
  echo " -y, --yes           skip emerge confirmation (opposite of default -a)"
  echo " --                  options provided after this are passed to emerge"
  exit 0
fi
if test -z "$NO_SYNC"; then
  check_is_root
  if ! emerge --sync; then
    exit $?
  fi
fi
if test -z "$PRETEND"; then
  if test "$(whoami)" != "root"; then
    echo "Requesting 'pretend' mode (you are not root)"
    PRETEND="-p"
  fi
fi
if emerge --update --newuse --deep @world @preserved-rebuild $ASK $EMERGE_ARGS; then
  emerge --depclean $ASK
fi
