#!/bin/sh
WATCH="$1";
function get_runlevel() {
  /sbin/runlevel | awk '{print $2}'
}
START_RUNLEVEL="$(get_runlevel)"
if test -z "$WATCH"; then
  WATCH="$(basename $0 | sed -e 's/watchdog-//')"
fi
if test -z "$WATCH"; then
  echo "Nothing to watch; try giving a command or making a link like $0-[command]"
  exit 1
fi
echo "watching $WATCH"

while true; do
  CURRENT_RUNLEVEL="$(get_runlevel)"
  if test "$CURRENT_RUNLEVEL" != "$START_RUNLEVEL"; then
    echo "runlevel changed from $START_RUNLEVEL to $CURRENT_RUNLEVEL; exiting"
    exit 0
  fi
  if test -z "$(pidof $WATCH)"; then
    $WATCH &
    sleep 5
  fi
  sleep 2
done
