#!/bin/bash
while true; do
  UPDATED=$(ps aux | grep mysql | grep -v grep | grep -v Toolbox |awk '{ $1=$3=$4=$5=$6=$7=$8=$9=$10=""; print $0}')
  clear
  echo "last updated: $(date)"
  echo
  if test -z "$UPDATED"; then
    echo "(no tempdb mysql processes found)"
  else
    echo "$UPDATED"
  fi
  sleep 0.5
done
