#!/bin/sh
WATCH="$1";
function get_runlevel() {
  /sbin/runlevel | awk '{print $2}'
}
START_RUNLEVEL="$(get_runlevel)"
if test -z "$WATCH"; then
  WATCH="$(basename $0 | sed -e 's/watchdog-//')"
fi
if test -z "$WATCH"; then
  echo "Nothing to watch; try giving a command or making a link like $0-[command]"
  exit 1
fi
LAST=$(echo $WATCH | sed -e 's/-/ /g' | awk '{print $(NF)}')
RESTART_DELAY=2
if test ! -z "$LAST"; then
  if test -z "$(echo $LAST | sed -e 's/[0-9]*//g')"; then
    RESTART_DELAY="$LAST"
    WATCH="$(echo $WATCH | sed -e 's/-[0-9]*$//g')"
  fi
fi

echo "watching $WATCH every $RESTART_DELAY seconds"
function check_runlevel_changed() {
  CURRENT_RUNLEVEL="$(get_runlevel)"
  if test "$CURRENT_RUNLEVEL" != "$START_RUNLEVEL"; then
    echo "runlevel changed from $START_RUNLEVEL to $CURRENT_RUNLEVEL; exiting"
    exit 0
  fi
}

while true; do
  check_runlevel_changed
  if test -z "$(pidof $WATCH)"; then
    sleep $RESTART_DELAY
    check_runlevel_changed
    $WATCH &
    sleep 5
  fi
  sleep 2
done
